/var/spool/slurmd/job1049706/slurm_script: line 6: --time=00:05:00: command not found
Started analysis of Sacc.R1.fastq.gz
Approx 5% complete for Sacc.R1.fastq.gz
Approx 10% complete for Sacc.R1.fastq.gz
Approx 15% complete for Sacc.R1.fastq.gz
Approx 20% complete for Sacc.R1.fastq.gz
Approx 25% complete for Sacc.R1.fastq.gz
Approx 30% complete for Sacc.R1.fastq.gz
Approx 35% complete for Sacc.R1.fastq.gz
Approx 40% complete for Sacc.R1.fastq.gz
Approx 45% complete for Sacc.R1.fastq.gz
Approx 50% complete for Sacc.R1.fastq.gz
Approx 55% complete for Sacc.R1.fastq.gz
Approx 60% complete for Sacc.R1.fastq.gz
Approx 65% complete for Sacc.R1.fastq.gz
Approx 70% complete for Sacc.R1.fastq.gz
Approx 75% complete for Sacc.R1.fastq.gz
Approx 80% complete for Sacc.R1.fastq.gz
Approx 85% complete for Sacc.R1.fastq.gz
Approx 90% complete for Sacc.R1.fastq.gz
Approx 95% complete for Sacc.R1.fastq.gz
Approx 100% complete for Sacc.R1.fastq.gz
Analysis complete for Sacc.R1.fastq.gz
Started analysis of Sacc.R2.fastq.gz
Approx 5% complete for Sacc.R2.fastq.gz
Approx 10% complete for Sacc.R2.fastq.gz
Approx 15% complete for Sacc.R2.fastq.gz
Approx 20% complete for Sacc.R2.fastq.gz
Approx 25% complete for Sacc.R2.fastq.gz
Approx 30% complete for Sacc.R2.fastq.gz
Approx 35% complete for Sacc.R2.fastq.gz
Approx 40% complete for Sacc.R2.fastq.gz
Approx 45% complete for Sacc.R2.fastq.gz
Approx 50% complete for Sacc.R2.fastq.gz
Approx 55% complete for Sacc.R2.fastq.gz
Approx 60% complete for Sacc.R2.fastq.gz
Approx 65% complete for Sacc.R2.fastq.gz
Approx 70% complete for Sacc.R2.fastq.gz
Approx 75% complete for Sacc.R2.fastq.gz
Approx 80% complete for Sacc.R2.fastq.gz
Approx 85% complete for Sacc.R2.fastq.gz
Approx 90% complete for Sacc.R2.fastq.gz
Approx 95% complete for Sacc.R2.fastq.gz
Analysis complete for Sacc.R2.fastq.gz
